# Dart
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']
hook_add = '''
  let g:dart_style_guide = 2
  let g:dart_format_on_save = 1 

  function! TriggerFlutterHotReload() abort
    silent execute '!kill -SIGUSR1 $(pgrep -f "[f]lutter_tool.*run")'
  endfunction
  autocmd! BufWritePost *.dart call TriggerFlutterHotReload()
'''
