name: macos-setup
on: push
jobs:
  macos-setup:
    name: setup macos
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: macos.sh
        run: curl -sS https://raw.githubusercontent.com/jiroshin/dotfiles/master/install/macos.sh | sh
